### PR TITLE
Start of migrate to hapi 8

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by kpdecker** [comment]
@geek you still looking at this?

**Comment by geek** [comment]
@kpdecker haven't been looking into it lately :/

**Comment by nvcexploder** [comment]
@geek and @kpdecker : need me to check this out?

**Comment by kpdecker** [comment]
That would be awesome.

**Comment by nvcexploder** [comment]
K - then I'll start taking a look very soon. :)

**Comment by kpdecker** [comment]
Released in 1.1.0

**Pull request closed without merging**
